I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 306, in script
    troll "What's a silly billy goat like you doing on my bridge all by yourself?"
Exception: Sayer 'troll' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 306, in script
    troll "What's a silly billy goat like you doing on my bridge all by yourself?"
  File "/Users/davidhan/Documents/renpy-7.1.3-sdk/renpy/ast.py", line 650, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/davidhan/Documents/renpy-7.1.3-sdk/renpy/ast.py", line 560, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'troll' is not defined.

Darwin-18.0.0-x86_64-i386-64bit
Ren'Py 7.1.3.1092
Labyrinth 1.0
Tue Apr 30 11:47:10 2019
