I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 252, in script
    if minotaur_attackr_option == 1:
  File "game/script.rpy", line 252, in <module>
    if minotaur_attackr_option == 1:
NameError: name 'minotaur_attackr_option' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 252, in script
    if minotaur_attackr_option == 1:
  File "/Users/davidhan/Documents/renpy-7.1.3-sdk/renpy/ast.py", line 1762, in execute
    if renpy.python.py_eval(condition):
  File "/Users/davidhan/Documents/renpy-7.1.3-sdk/renpy/python.py", line 1944, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/davidhan/Documents/renpy-7.1.3-sdk/renpy/python.py", line 1937, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 252, in <module>
    if minotaur_attackr_option == 1:
NameError: name 'minotaur_attackr_option' is not defined

Darwin-18.0.0-x86_64-i386-64bit
Ren'Py 7.1.3.1092
Labyrinth 1.0
Thu Apr  4 11:46:41 2019
