I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 580, in script
    palyer "What are you?"
Exception: Sayer 'palyer' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 580, in script
    palyer "What are you?"
  File "/Users/davidhan/Documents/renpy-7.1.3-sdk/renpy/ast.py", line 650, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/davidhan/Documents/renpy-7.1.3-sdk/renpy/ast.py", line 560, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'palyer' is not defined.

Darwin-18.0.0-x86_64-i386-64bit
Ren'Py 7.1.3.1092
Labyrinth 1.0
Wed May  8 13:32:42 2019
